# Generated by Django 5.2.3 on 2025-06-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_processedimage_input_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='zero_filled_preview',
            field=models.ImageField(blank=True, upload_to='previews/', verbose_name='零填充图像预览'),
        ),
    ]
