# Generated by Django 5.2.5 on 2025-09-13 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_image_article_keywords_article_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mri', 'MRI'), ('pet', 'PET'), ('ct', 'CT'), ('ultrasound', '超声'), ('xray', 'X光'), ('other', '其他')], max_length=50, unique=True, verbose_name='数据类型')),
                ('description', models.TextField(blank=True, help_text='介绍该数据类型的特点和应用场景', verbose_name='类型描述')),
                ('icon', models.CharField(default='fa-image', help_text='FontAwesome图标名称', max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#007bff', help_text='十六进制颜色代码', max_length=7, verbose_name='主题色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据类型',
                'verbose_name_plural': '数据类型',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='model_type',
            field=models.CharField(choices=[('super_resolution', 'DFAM (超分辨率重建)'), ('style_transfer', 'WKGM (风格迁移)')], default='super_resolution', max_length=50, verbose_name='模型类型'),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='如：医院A、研究机构B等', max_length=200, verbose_name='数据源名称')),
                ('source_description', models.TextField(blank=True, help_text='详细介绍该数据源的背景信息', verbose_name='数据源描述')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='机构名称')),
                ('collection_date', models.DateField(blank=True, null=True, verbose_name='收集日期')),
                ('data_quality', models.CharField(choices=[('excellent', '优秀'), ('good', '良好'), ('fair', '一般'), ('poor', '较差')], default='good', max_length=50, verbose_name='数据质量')),
                ('is_public', models.BooleanField(default=True, help_text='是否允许所有用户访问', verbose_name='公开访问')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.datatype', verbose_name='数据类型')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'ordering': ['-created_at'],
                'unique_together': {('data_type', 'source_name')},
            },
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(help_text='支持DICOM、NIfTI、MAT等格式', upload_to='data_files/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('dicom', 'DICOM'), ('nifti', 'NIfTI'), ('mat', 'MATLAB'), ('raw', '原始数据'), ('image', '图像文件'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(default=0, help_text='字节', verbose_name='文件大小')),
                ('file_description', models.TextField(blank=True, verbose_name='文件描述')),
                ('patient_id', models.CharField(blank=True, help_text='匿名化患者标识', max_length=100, verbose_name='患者ID')),
                ('scan_date', models.DateTimeField(blank=True, null=True, verbose_name='扫描日期')),
                ('scan_parameters', models.TextField(blank=True, help_text='如：TR、TE、层厚等参数信息', verbose_name='扫描参数')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔的标签', max_length=500, verbose_name='标签')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='下载次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.datasource', verbose_name='数据源')),
            ],
            options={
                'verbose_name': '数据文件',
                'verbose_name_plural': '数据文件',
                'ordering': ['-created_at'],
            },
        ),
    ]
