# Generated by Django 5.2.5 on 2025-09-13 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_datatype_alter_processedimage_model_type_datasource_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(max_length=100, unique=True, verbose_name='上传ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小')),
                ('uploaded_size', models.BigIntegerField(default=0, verbose_name='已上传大小')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('processing', '处理中'), ('completed', '完成'), ('failed', '失败')], default='uploading', max_length=20, verbose_name='状态')),
                ('progress', models.FloatField(default=0.0, verbose_name='进度百分比')),
                ('upload_speed', models.FloatField(default=0.0, help_text='KB/s', verbose_name='上传速度')),
                ('estimated_time', models.IntegerField(default=0, help_text='秒', verbose_name='预计剩余时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '上传进度',
                'verbose_name_plural': '上传进度',
                'ordering': ['-created_at'],
            },
        ),
    ]
