# Generated by Django 5.2.5 on 2025-10-21 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_uploadprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='model_type',
            field=models.CharField(choices=[('super_resolution', 'DFAM'), ('style_transfer', 'WKGM')], default='super_resolution', max_length=50, verbose_name='模型类型'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(choices=[('student', '学生'), ('researcher', '研究者'), ('employee', '企业员工'), ('hobbyist', '爱好者'), ('other', '其他')], default='student', max_length=20, verbose_name='身份')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='所属机构')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
    ]
