# Generated by Django 4.2 on 2025-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processedimage", old_name="created_time", new_name="created_at",
        ),
        migrations.RemoveField(model_name="processedimage", name="title",),
        migrations.AlterField(
            model_name="processedimage",
            name="model_type",
            field=models.CharField(
                choices=[("super_resolution", "超分辨率"), ("style_transfer", "风格迁移")],
                default="super_resolution",
                max_length=50,
                verbose_name="模型类型",
            ),
        ),
        migrations.AlterField(
            model_name="processedimage",
            name="original_image",
            field=models.FileField(upload_to="original/", verbose_name="原始图像"),
        ),
        migrations.AlterField(
            model_name="processedimage",
            name="processed_image",
            field=models.FileField(
                blank=True, upload_to="processed/", verbose_name="处理后图像"
            ),
        ),
        migrations.AlterField(
            model_name="processedimage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="处理状态",
            ),
        ),
    ]
