# Generated by Django 4.2 on 2025-03-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_created_time_processedimage_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedimage",
            name="input_preview",
            field=models.ImageField(
                blank=True, upload_to="previews/", verbose_name="输入图像预览"
            ),
        ),
        migrations.AddField(
            model_name="processedimage",
            name="output_preview",
            field=models.ImageField(
                blank=True, upload_to="previews/", verbose_name="输出图像预览"
            ),
        ),
        migrations.AddField(
            model_name="processedimage",
            name="psnr_value",
            field=models.FloatField(blank=True, null=True, verbose_name="PSNR"),
        ),
        migrations.AddField(
            model_name="processedimage",
            name="ssim_value",
            field=models.FloatField(blank=True, null=True, verbose_name="SSIM"),
        ),
    ]
