# Generated by Django 5.2.3 on 2025-06-16 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_processedimage_zero_filled_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('mask_file', models.FileField(upload_to='masks/', verbose_name='Mask文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '欠采样Mask',
                'verbose_name_plural': '欠采样Mask',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='processedimage',
            name='selected_mask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.mask', verbose_name='选择的Mask'),
        ),
    ]
