# Generated by Django 5.2.3 on 2025-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mask_processedimage_selected_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='文章图片'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, help_text='用逗号分隔多个关键字', max_length=200, verbose_name='关键字'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, verbose_name='网站连接'),
        ),
        migrations.AlterField(
            model_name='processedimage',
            name='model_type',
            field=models.CharField(choices=[('super_resolution', 'DFAM'), ('style_transfer', 'WKGM')], default='super_resolution', max_length=50, verbose_name='模型类型'),
        ),
    ]
