# Generated by Django 4.2 on 2025-03-01 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "created_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="创建时间"
                    ),
                ),
                (
                    "modified_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "文章",
                "verbose_name_plural": "文章",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="ProcessedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                (
                    "original_image",
                    models.ImageField(upload_to="original/", verbose_name="原始图片"),
                ),
                (
                    "processed_image",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        upload_to="processed/",
                        verbose_name="处理后的图片",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("style_transfer", "风格迁移"),
                            ("super_resolution", "超分辨率"),
                            ("object_detection", "目标检测"),
                        ],
                        max_length=50,
                        verbose_name="处理模型",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="处理状态"
                    ),
                ),
            ],
            options={"verbose_name": "图像处理", "verbose_name_plural": "图像处理",},
        ),
    ]
